# Generated by Django 5.0.3 on 2026-05-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
